
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-demo
  namespace: default
spec:
  replicas: 4                     # this is number of pods
  selector:
    matchLabels:
      app: nodejs-demo
  template:
    metadata:
      labels:
        app: nodejs-demo
    spec:
      containers:
      - name: nodejs-demo-app
        # pulling image from my DockerHub
        image: 166480307013/nodejs-demo:latest
        imagePullPolicy: Always

        resources:
          limits:
            memory: 64Mi
            cpu: "250m"
          requests:
            memory: 32Mi
            cpu: "200m"
        # specify the container port
        ports:
        - containerPort: 30002


---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-demo-entrypoint
  namespace: default
spec:

  type: LoadBalancer
  selector:
    app: nodejs-demo
  # The range of valid ports in kubernetes is 30000-32767
  ports:

    - name: http
      protocol: TCP
      port: 80             # this is service port 80
      targetPort: 30002
      # nodePort: 30003      # this is for when using type: NodePort
    - name: https
      protocol: TCP
      port: 443            # this is service port 443
      targetPort: 30002
      # nodePort: 30004      # this is for when using type: NodePort
